branches:
  except:
    - flatpak

image:
  - Ubuntu1804

clone_folder: ~/GameHub

build_script:
  - sh: bash appimage/build.sh build && bash appimage/build.sh appimage

install:
  - sh: bash appimage/build.sh deps

test: off

artifacts:
  - path: build/appimage/GameHub*.AppImage*
    name: AppImage
