version: 0.11.1-{build}-{branch}

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

branches:
  except:
    - flatpak

image:
  - Ubuntu1604
  - Ubuntu1804

clone_folder: ~/build/GameHub
clone_depth: 1

build_script:
  - sh: bash appimage/build.sh build_deb
  - sh: bash appimage/build.sh build
  - sh: bash appimage/build.sh appimage
  - sh: bash appimage/build.sh appimage_tweak
  - sh: bash appimage/build.sh appimage_bundle_libs
  - sh: bash appimage/build.sh appimage_checkrt
  - sh: bash appimage/build.sh appimage_pack

install:
  - sh: bash appimage/build.sh deps

test: off

artifacts:
  - path: build/*/*.deb
    name: deb
  - path: build/appimage/GameHub*.AppImage*
    name: AppImage

deploy:
  - provider: GitHub
    description: |
        CI build

        * Use `bionic` packages for recent distros (>= Ubuntu 18.04)
        * Use `xenial` packages for older distros (>= Ubuntu 16.04)
    auth_token:
        secure: J2LCcNeVYvzbvHRa/LChp+SmN6UKbg1ELsA4jmxnObCbX+ZyZ9DFH+S2aQIoA3dG
    artifact: deb,AppImage
    draft: false
    prerelease: true
