version: 0.11.1-{build}-{branch}

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

branches:
  except:
    - flatpak

image:
  - Ubuntu1804

clone_folder: ~/build/GameHub
clone_depth: 1

build_script:
  - sh: dpkg-buildpackage -b -us -uc
  - sh: bash appimage/build.sh build && bash appimage/build.sh appimage

install:
  - sh: bash appimage/build.sh deps

test: off

artifacts:
  - path: ../*.deb
    name: deb
  - path: ../*.ddeb
    name: deb-dbgsym
  - path: build/appimage/GameHub*.AppImage*
    name: AppImage

deploy:
  - provider: GitHub
    description: CI build (AppImage)
    auth_token:
        secure: J2LCcNeVYvzbvHRa/LChp+SmN6UKbg1ELsA4jmxnObCbX+ZyZ9DFH+S2aQIoA3dG
    artifact: deb,deb-dbgsym,AppImage
    draft: false
    prerelease: true
